fix(package/pypi): response header based on PEP691 (#13731)
The response Content-Type doesn't match PEP691 so `uv` is rejecting it.

```
error: Unsupported `Content-Type` "application/json" for ...
       Expected JSON or HTML.
```

Resolves https://codeberg.org/forgejo/forgejo/issues/13703

Co-authored-by: trim21 <i@trim21.me>
Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/13731
Reviewed-by: oliverpool <oliverpool@noreply.codeberg.org>
Reviewed-by: Gusted <gusted@noreply.codeberg.org>
(cherry picked from commit 869c2973f94f5a09cfa946ed576855f209013729)